### ISSUE TITLE
ENDED IN ERROR : element click intercepted

### ISSUE THREAD

**Issue by thibautflottat** [smf33/InstagramFollowerBot#1]
Hi ! It's me again. As your flickr tool is great, I wanted to try the Instagram one.

It crashes with this error :

`## ENDED IN ERROR : element click intercepted: Element <a class="gmFkV" href="/.../" tabindex="0">thibautflt</a> is not clickable at point (1067, 125). Other element would receive the click: <div class="RnEpo Yx5HN     " role="presentation">...</div>
  (Session info: chrome=87.0.4280.66)
OpenQA.Selenium.ElementClickInterceptedException: element click intercepted: Element <a class="gmFkV" href="/.../" tabindex="0">thibautflt</a> is not clickable at point (1067, 125). Other element would receive the click: <div class="RnEpo Yx5HN     " role="presentation">...</div>
  (Session info: chrome=87.0.4280.66)
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary 2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.InternalExecute(String driverCommandToExecute, Dictionary 2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebElement.Execute(String commandToExecute, Dictionary 2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebElement.Click()
   at InstagramFollowerBot.SeleniumWrapper.Click(String cssSelector) in /home/thibaut/web/InstagramFollowerBot/SeleniumWrapper.cs:line 142
   at InstagramFollowerBot.FollowerBot.AuthLogin() in /home/thibaut/web/InstagramFollowerBot/FollowerBot.Actions.cs:line 213
   at InstagramFollowerBot.FollowerBot.Run() in /home/thibaut/web/InstagramFollowerBot/FollowerBot.cs:line 68
   at InstagramFollowerBot.Program.Main(String[] args) in /home/thibaut/web/InstagramFollowerBot/Program.cs:line 18
`

using `dotnet run`, and the same using `docker-compose up` :

`bot_1  | ## ENDED IN ERROR : element click intercepted: Element <a class="gmFkV" href="/.../" tabindex="0">thibautflt</a> is not clickable at point (977, 125). Other element would receive the click: <div class="RnEpo Yx5HN     " role="presentation">...</div>
bot_1  |   (Session info: chrome=87.0.4280.66)
bot_1  | OpenQA.Selenium.ElementClickInterceptedException: element click intercepted: Element <a class="gmFkV" href="/.../" tabindex="0">thibautflt</a> is not clickable at point (977, 125). Other element would receive the click: <div class="RnEpo Yx5HN     " role="presentation">...</div>
bot_1  |   (Session info: chrome=87.0.4280.66)
bot_1  |    at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
bot_1  |    at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary 2 parameters)
bot_1  |    at OpenQA.Selenium.Remote.RemoteWebDriver.InternalExecute(String driverCommandToExecute, Dictionary 2 parameters)
bot_1  |    at OpenQA.Selenium.Remote.RemoteWebElement.Execute(String commandToExecute, Dictionary 2 parameters)
bot_1  |    at OpenQA.Selenium.Remote.RemoteWebElement.Click()
bot_1  |    at InstagramFollowerBot.SeleniumWrapper.Click(String cssSelector) in /src/SeleniumWrapper.cs:line 144
bot_1  |    at InstagramFollowerBot.FollowerBot.AuthLogin() in /src/FollowerBot.Actions.cs:line 214
bot_1  |    at InstagramFollowerBot.FollowerBot.Run() in /src/FollowerBot.cs:line 70
bot_1  |    at InstagramFollowerBot.Program.Main(String[] args) in /src/Program.cs:line 18
instagramfollowerbot_bot_1 exited with code 255
`

I don't know if it can help, but the coordinates of the not clickable point are not the same each time I test. I am using the last stable version of chrome on Arch Linux. Thank you ! :)

**Comment by smf33** [comment]
Hi, the AI branch was more up to date :-), i pushed a change, could you try again ?
Watch out for insta bot, chromedrivers tend to have far more timeout than flickrbot, and insta is worse than flickr :-( far more page/css update, and a efficient bot detection. read the error crash message well : unusual connection detection or action blocked must be managed (by doing a visual connection for the 1st, and for the second, make less action and do a breack of 2 days with this account).
Good luck !

**Comment by thibautflottat** [comment]
Nothing changed unfortunately.

I have no knowledge with this kind of tool, but when I use "dotnet run", it open a chrome window, and I can see the crash occurs on the 4th dialog box. First one is for cookies, second one for connexion, third one for saving login/passwd, and the fourth is about notifications. 

If I quickly click on "turn on" the script does not crash. Maybe your tools only consider less than 4 actions to perform ?

**Comment by smf33** [comment]
Could you check if u have last code version ? Else send the log with max
info pls

**Comment by smf33** [comment]
My bad, issue occured with new session, and not "saved" session.
Allow me to fix this quickly and then update your source or docker image.

**Comment by smf33** [comment]
My bad, issue occured with new session, and not "saved" session.
Could you get last code version or docker image and retry now ?

**Comment by thibautflottat** [comment]
It's working now using "dotnet run", but still failing using "docker-compose up". Here is the full log : https://hastebin.com/equvujiwow.xml

Let me now if you need more informations ! ;)

**Comment by smf33** [comment]
hi 
i added a waiter between click, you can see on your dump that the "Turn on Notifications" was still displayed even if the step of closing it was pass before, but to fast, the bot didn t let time to the website to display it.*
Can you confirm me it s ok with last code update on both execution context ?

**Comment by smf33** [comment]
without any feedback on my proposed fix, i supose it s close now.
